name: CI/CD Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build SQL scripts
        run:
          mkdir -p build/sql
          mysql -h localhost -u root -p Somethingbetter123 < scripts/create_database.sql
          mysql -h localhost -u root -p Somethingbetter123 < scripts/create_tables.sql
          mysqldump -h localhost -u root -p Somethingbetter123 database > build/sql/database_backup.sql

  build-vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: WebShop
        run: npm install
      - name: Build Vue3 application
        working-directory: WebShop
        run: npm run build
  deploy:
      needs: [build-sql, build-vue]
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to production
          run: |
